# Generated by Django 3.2.7 on 2021-09-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210915_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='blue',
        ),
        migrations.RemoveField(
            model_name='color',
            name='green',
        ),
        migrations.RemoveField(
            model_name='color',
            name='red',
        ),
        migrations.AddField(
            model_name='color',
            name='hex_value',
            field=models.CharField(default='#001122', max_length=7),
        ),
    ]
