# Generated by Django 3.2.7 on 2021-09-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_customsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.color')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomSettings',
        ),
    ]
